---
deployment:
  tasks:
    - export DEPLOYPATH=/home/imvdeme1/public_html/beezper
    - /bin/cp -R public/css/ $DEPLOYPATH
    - /bin/cp -R public/img/ $DEPLOYPATH
    - /bin/cp -R public/js/ $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon.ico $DEPLOYPATH
    - /bin/cp public/mix-manifest.json $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
    - /bin/cp public/web.config $DEPLOYPATH